export const CREATE_UTILIZADOR = "CREATE_UTILIZADOR";

export const RETRIEVE_UTILIZADORES = "RETRIEVE_UTILIZADORES";

export const UPDATE_UTILIZADOR = "UPDATE_UTILIZADOR";

export const DELETE_UTILIZADOR = "DELETE_UTILIZADOR";